### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by Andrew2a1** [Uszczi/game_OSM#1]
1. Pacman

Pytania:
 - Czy duchy i pacman to piksele czy bitmapa
 - to samo pytanie do labiryntu
 
 duchy, pacman i labirynt jako pixmapy
 
 - Wyświetlanie bitmap
 - Poruszanie się bitmapą po ekranie
 
 -> Jak ma być reprezentowany labirynt?
 - Tablica 2D gdzie każde pole zawiera możliwe przejścia
 
 -> Algorytmy dla duchów
 - A*, każdy duszek inaczej śledzi pacmana
 
_"""
- [x]  Pixmapy
- [x] Tablica z labiryntem
- [x] poruszanie się pacmanem
- [ ] Duchy
- [ ] Jedzenie kulek
- [ ] Zbieranie punktów
- [ ] Menu
- [ ] Życia
 """_

**Comment by Uszczi** [comment]
### Mateusz
- [] Ulepszysz poruszanie się Pacmanem
- [] Dodac Ducha chodzacego w kółko 
### Adam
- [] Refaktoryzacja ?? 

### Not Assigned
- [] Dodać resetowanie poziomy
- [] Dodać kulki
- [] Dodać zbieranie kulek i updatowanie punktacji
- [] Dodać wyświetlanie życia


#### Not now
- [] Algorytm do duchów / czeka na duchy 
- [] Dodać kolizję z Duchami / czeka na duchy 
- [] Dodac tryb ucieczki duchow
